language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- iojs
deploy:
  matrix: 
  provider: npm
  api_key:
    secure: FCD//FFuBwnFcWBjRxRJYuSwO44s9j1TKR8MhaGxy675dZeG5F55zrPCPcU1C2cBjceYaL1jx1hZYBtmYyVZIf52LTY5qyMssbsASakGJnyo0N8vlkM4MGpWFkoyAlxuRWAbDWmq/1QVZCKOLctICMSL1uXb2zUTAwcJ4n7UxxsYN4YkzZxwC1KW5vrCsabEPx2O1Q0V2eOCi4EeALgJ1tOOboNTXXUAE6wEUKNP7jT0Vq92VH51Z0GPxd/436JCscwiB0RbWWJsjjjvxC8hhdyyMPRO6PL6WC0UUbd2X5cwRGz9MXtkw9YqvqoZxk/90fyEShyd0XLVIzK2LGQvD12K59uyF/dgN6uFwytOYrLUUww7vDmVjO3kZsIjoqnXa2Hz7/IWT9IY4FpSDu05xdjFNZzAyrY7cnTBQZ0K9ECR7CqWcTjLG0wEEnOaNXOU97WBicckxPr844f7K2vRV2UAED/jOYWcYiVlDgXIDw7PN34O59ZAzYsa7lwLnaktC5jPbU8y0WLgwQGyAQzzI5ldbtNOsZiaSuMDDBmNp/1L3f1hWlLNP14El2NpLV1oVHLraOYR2YSGKy/RhGVwojHaNBO20Zc86+Lcok8GMG3vWvqXBhbzCq1NLVt/jJN/NrkPY4xbr3Xq2sJqNo4BKkG3cf8NtAerpd9/qjpe6wY=
  email:
    secure: O6uCatt+Ukqtr2NDId1X43w4muwQWlLUJOF5OrPUwWa9fpd+wLhEIQlUYBmcA2nm0xC4prIgxmJJ4wWNLk+vgQLIzVTaD0dnyJXCeRn+qWFd7/0VoaIzzrr6wLdwkM/9MBH6Ds05X0UP0EG1+9f7bPoN9FrH79EEY5L8Z2WsoPgOOAjynog9ou9neSOLuYjrilR5q6Ws83LIPuiKpdQL+4DmU94+x05TdmECJpXQV81MrIjZD5A52/xMwztmhsvKJ++9gDhT7Aal0wGasNcauMTduPUxCR4xHiU9g03D+QWV7CBlIRDSXAyHN/E3BXisDS9xRq747UHj0S6fL3xMdgSkgod323W6O303w29C1idjlgd2qrS/FkTJ8p6NN8XYlO31VqBlXyGo6vfqZPH0tsIYvlkcFlDjYu9ajiSDny1/qWXZeHmsemD1fvvRgCH48ABfWa+dYkBIzADg25TLm1nI9oMKJrtcHiv+dAUgSaeEx7wVI0ZTd2M7q1xSxZAmu9mmkl5H3CRQOjFFkYw0nNPT2COS4VTRW4OSu8QdZOj+CcyodHWP01uIwIra5hHcz3BEiX+dTDmC+RDnqPEZ4sCHYrGrVZOt/VM0EWtGvjsSZFZ6sxJngCTE3hIKytkF56o8OgwUTmnvz3P7B5WPKQOqTpel86YrDePt0ePozz0=
