language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- iojs
deploy:
- provider: npm
- email:
  - secure: "V9i7avbeW/V81ZEQs1tg8cRr1vJrveukEotVUsf0UH9LLjgJVHMrkl0vxYO1iAr7/iAVyqlgVLD+IIOwH+uxL3jo6STg0w+PsvLQeZ0gU0T+V27XYkBaFZiubXi05xC7AZWXyCj7GJlqVwAjghYCQv/5vAH7HHhOOPDrhYHC7ypy32OiS7yKOH6g2nXeJ9iViVDsBO6iFduqhzFB27XAReeMpYv+ADZxgiNLlwgbumuxPNM8V0kgTs7s5tfAhL4y5/siK62ZncWujkSL1G0GmCzfEViYvpME7Atw1BF8QUAg6Hu95l5ftqhdUY46sQ6NsIbT3Ct8rHvS2Tj3GFTc8p2+gscTO21S2TzsIFc71VZJDCqjdMM0Zyk2/d/6k062dlMTv+pElnK7PhMJpKOn83bZaxiMz6MFBPqV1xyY8KqJkBjrjSqpBWCaS0Q9y/GEuP0ypNcX3kU4oSpN3wQLq+oIkQJAyDUKRLL4qN1JHFD+EEctBfSIJgihGh2wO0lRj/qQW3vV9GCFVW7wnRYFeDd/sdk7CiVsDyyRiwV/9oJ/58Z9YeRnG4WvON8nWgYKLKNW1fiXCVz+yX+jSfualA4V0Zpad4vKETzk2j+zUr1dSWJY3xJjsU/T2a+evRZunDbhPNTKCSk28MQuDqTpuRD+n51uMZ+8+Xkw0tLGyuA="
- password:
  - secure: "hZX6/jQykhljwWnmtZqDRdOpSaLgorTvKC1HJ53Lvo0zlUookSW8OA5BVEu297SX7Q/ANNLcoZt1V84fepaW16R7s4JhkvU4mCz/wsFbEroDVdegOMbiRKJKUsy50ALR2lf8Dt34xfudTzJdxMVDLGI0dlFwtSgaUDVOH8uXbyn5j1ldDgyXWx3g18Ngxl85lhIzpiPgvAcASgJsQk1qg76rAQOUpw8hYp0K+os/+4yJhhsk59neQNhXcKGb4b/TOHEgKc5w7EoElbwXC0Yy3IX+7BDf8fMVyRkFpaiTkeV5n6Raow+DyZo0Z+WHq7yH/hLo4Csq89gL3qeCshYcgeNfr0QSz2eSyGCgSDLynEBaconTiNqt50VnfEiE7Kx+SmgWN6cwLbv2EWLczbWeSgwCMiMjUV1xN2eG0WQyRAS4DTJGU6nFdBRTq4IeTER9R1KgcTu1iB9i9eH3BZy8Bd+WQg15IYLMrJFpLk050LqsakA6nIl+Lz4h8/eQLj78xnphNZZuLO6nu9FmjTnBHNbjegHIhtBl0W+Zk4pQ8RDdxvu80sTtTvKoSn8qpT2foA5A02fzeQzBI32sdqNoRpKVRShxb1ehNXvu6i6EjbJ+Y7CeGzLREHqi28YC9HmKw9CJUtNjWKawRh+sG8FjP8CQWexgkmwt5sB5DtdBPMs="