language: node_js
node_js:
- '4.1'
before_deploy:
- git config user.email "njenan@gmail.com"
- git config user.name "Travis CI"
- npm version patch
deploy:
  provider: releases
  api_key:
    secure: bB18rdp7YFGn+6c4RU8+ISJIjxlX0/yUsYuyslM6QUZq9eBRSR0l/1JfjLby407+oaEKPCsCRHWdX3hKyhC33BnMPPx1AmDsC2kzqbCG4/StaSGC3PtONNRMm5bVeNtpBNP1HA3xaFrNtT7PYfD6N9iJlz+f327u/80Tr0QynTM+cr8Az5X7mUV+X797GsqXmB1sTJpC1MYdQrvcy5QCydd6eVvuN6P76lJ1UDpF9qw26FDjbl1aeIb4cUCD/oF3U+hWaXZgOGXDGpDLr+AcFZpy5W3T23nUTKXpdv4H0iBStPmNE58TxrqsyODaRxWXD31eJr44Spj1LDWd3tkn9bAMut5DVqTnzDeDySrtjCJSih3/o6erTnHyp1/Rx91nVuHiacCyurgkIL2wg1JHR9oHHLx5/DSJfRZiMDSr8nu5pYOGKxXmlrBEi4eg8+gSPvwgqKcO6cSNs6G+sJA0pgJIAM3MppjrDmMNW+t6ugwvvNHimK/9aIMxWv9cPsKXZfxERXw+OAJIkNn/Q7R7MhNxvMaPHQLPdTpNI31T3rEeV/VJGa2JrwzXpwJAVfmnD6M6mJhNa/tqSOFh4QpmdqvL+VBAa8iVBH854nRxzWDc8u7S1v45tjxCCpOEZ8JxE+uK1iNcpyak79GIKKF4RJsWRPOLpEp1xfkkH/kBA00=
  file: package.json
  on:
    repo: njenan/Razorback
