language: node_js
node_js:
- '4.1'
before_deploy: npm version patch
deploy:
  provider: npm
  email: njenan@gmail.com
  api_key:
    secure: fMyXcwfVnmJzZL3Q9Yw17mgpQX1MCTNEzLkwJ4GTDGXz2IEWsGpDagXstkvjj8XSNUBoeHQZ3SDLx6L1DQ+ii6IgFR8vxe6C17fuYikLM+RX90VU5lxKmubyIlqnqM83eqIxHC+uics/TAPJdcGwZ5gptpUBHzDH58oU9B7GdM4pYFKGhqGQxsGvR57Tp3xEs97+NBa2uUwHxsk48m5zp8hdxy+Th4EsYHELwi6jLJHWEGcrHaAmA+mguxJmGeg10WQAsZm29awEmHiufMlN6x18wDjcKAFRnH/p3rsb+p7XcaUQ1IqUqiFk8jNNSNQm4XEOJ1ChFwLCdlmoB/JpOOjN8ytUyB6TRL3/MsC86hQV9U6z1E7Hx79mRXq2p0xucQMCb972KMnsJDzZkXf0v6d/eGkQY+FK/8t9+EbLBN5Amn9X9KcCsvXB6TTJJ+8RCfqSrNOYCDNuq0cDQQVCwQJ8hxd8gkuk+1tUOUUsV+0o7TzoMSQK9HfF2/BrVaMV9TDPoPhlnq7ndBOVcdXLXfZF5fASwR8VMCMUB0O5tYy45fSGgiocfmssm7VNQzEppeGTifII2dSKFbOjzgZZZHs+AqMYA/AKd/wIV659vtWl84J7nzcAp1yvHa0s6ExoDSJO+WGOuGYVva5r2D57mKCjDu5FIe86f3bisYkRoRA=
  on:
    repo: njenan/Razorback
